// BookSyncService - the client half of Vimbai shared-Book cloud sync.
//
// Design (book-design.md, self-hosting + sync chapters):
//  * Every Book has its own local SQLite database on the device, so
//    Books are cryptographically and logically partitioned. A family
//    admin can never read your Personal Book.
//  * Personal Books never leave the device.
//  * Shared Books sync end-to-end encrypted with the book-sync
//    service: locally queued entries are AES-256-GCM encrypted with
//    the Book key before leaving the device, and the server only
//    ever stores opaque blobs.
//  * Entries are append-only and immutable; the server assigns a
//    monotonically increasing per-Book sequence so delta pulls are
//    trivial and conflict-free.
//  * Metadata (book name, settings) syncs last-write-wins.
//
// The Book key is generated by the owner's device and wrapped (RSA)
// for each invited member; the unwrap happens on the member's device.

import 'dart:convert';
import 'dart:io';
import 'dart:math';
import 'dart:typed_data';

import 'package:http/http.dart' as http;
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:pointycastle/export.dart';
import 'package:sqflite/sqflite.dart';
import 'package:uuid/uuid.dart';

import 'package:vimbai_mobile_client/models/book_models.dart';

class BookSyncService {
  BookSyncService._();
  static final BookSyncService instance = BookSyncService._();

  static const String _kBaseUrl = String.fromEnvironment(
    'VIMBAI_BOOK_SYNC_URL',
    defaultValue: 'http://10.0.2.2:8080/book-sync',
  );

  http.Client _client = http.Client();
  String? _authToken;

  final Uuid _uuid = const Uuid();
  Database? _metaDb; // book registry + keys
  final Map<String, Database> _bookDbs = {};

  // -- registry ----------------------------------------------------------

  Future<Database> _meta() async {
    if (_metaDb != null) return _metaDb!;
    final dir = await getDatabasesPath();
    _metaDb = await openDatabase(
      p.join(dir, 'vimbai_books.db'),
      version: 1,
      onCreate: (db, _) async {
        await db.execute('''
          CREATE TABLE registry (
            book_id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            tier TEXT NOT NULL,
            description TEXT DEFAULT '',
            role TEXT NOT NULL,
            status TEXT NOT NULL,
            local_seq INTEGER NOT NULL DEFAULT 0,
            device_id TEXT DEFAULT '',
            book_key TEXT DEFAULT '',
            last_meta_sync REAL NOT NULL DEFAULT 0
          )
        ''');
      },
    );
    return _metaDb!;
  }

  Future<Database> _bookDb(String bookId) async {
    if (_bookDbs.containsKey(bookId)) return _bookDbs[bookId]!;
    final dir = await getDatabasesPath();
    final db = await openDatabase(
      p.join(dir, 'vimbai_book_$bookId.db'),
      version: 1,
      onCreate: (d, _) async {
        await d.execute('''
          CREATE TABLE entries (
            entry_id TEXT PRIMARY KEY,
            seq INTEGER,
            user_id TEXT,
            created_at REAL NOT NULL,
            ciphertext TEXT NOT NULL,
            pending INTEGER NOT NULL DEFAULT 0
          )
        ''');
        await d.execute('''
          CREATE TABLE meta (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL,
            updated_at REAL NOT NULL
          )
        ''');
      },
    );
    _bookDbs[bookId] = db;
    return db;
  }

  // -- auth --------------------------------------------------------------

  /// JWT from the existing login flow; sent as Bearer to the gateway.
  void setAuthToken(String token) => _authToken = token;

  Map<String, String> get _headers => {
        'Content-Type': 'application/json',
        if (_authToken != null) 'Authorization': 'Bearer $_authToken',
      };

  Uri _u(String path, [Map<String, String>? q]) =>
      Uri.parse('$_kBaseUrl$path').replace(queryParameters: q);

  // -- crypto ------------------------------------------------------------

  /// Random 256-bit AES book key, base64-encoded.
  String generateBookKey() {
    final rnd = FortunaRandom();
    final seed = Uint8List.fromList(
      List<int>.generate(32, (_) => Random.secure().nextInt(256)),
    );
    rnd.seed(KeyParameter(seed));
    final key = rnd.nextBytes(32);
    return base64Encode(key);
  }

  Uint8List _aesKey(String bookKeyB64) =>
      Uint8List.fromList(base64Decode(bookKeyB64));

  /// AES-256-GCM encrypt a JSON payload with the Book key.
  String encryptPayload(String bookKeyB64, Map<String, dynamic> data) {
    final gcm = GCMBlockCipher(AESFastEngine())
      ..init(
        true,
        AEADParameters(
          KeyParameter(_aesKey(bookKeyB64)),
          128,
          Uint8List(12),
          Uint8List(0),
        ),
      );
    final plain = Uint8List.fromList(utf8.encode(jsonEncode(data)));
    final out = gcm.process(plain);
    return base64Encode(out);
  }

  /// Decrypt a payload fetched from the sync server.
  Map<String, dynamic> decryptPayload(String bookKeyB64, String b64) {
    final gcm = GCMBlockCipher(AESFastEngine())
      ..init(
        false,
        AEADParameters(
          KeyParameter(_aesKey(bookKeyB64)),
          128,
          Uint8List(12),
          Uint8List(0),
        ),
      );
    final clear = gcm.process(Uint8List.fromList(base64Decode(b64)));
    return jsonDecode(utf8.decode(clear)) as Map<String, dynamic>;
  }

  // -- books -------------------------------------------------------------

  Future<List<VBook>> refreshBooksFromServer() async {
    final r = await _client.get(_u('/books'), headers: _headers);
    if (r.statusCode != 200) {
      throw Exception('Failed to load books: ${r.statusCode}');
    }
    final books = (jsonDecode(r.body) as Map<String, dynamic>)['books']
        as List<dynamic>;
    final meta = await _meta();
    final List<VBook> result = [];
    for (final b in books) {
      final book = VBook.fromJson(b as Map<String, dynamic>);
      await meta.insert(
        'registry',
        {
          'book_id': book.id,
          'name': book.name,
          'tier': book.tier,
          'description': book.description,
          'role': book.yourRole,
          'status': book.membershipStatus,
          'last_meta_sync': DateTime.now().millisecondsSinceEpoch / 1000.0,
        },
        conflictAlgorithm: ConflictAlgorithm.replace,
      );
      result.add(book);
    }
    return result;
  }

  Future<List<VBook>> localBooks() async {
    final meta = await _meta();
    final rows = await meta.query('registry');
    return rows.map((r) {
      return VBook(
        id: r['book_id'] as String,
        name: r['name'] as String,
        tier: r['tier'] as String,
        description: r['description'] as String? ?? '',
        yourRole: r['role'] as String? ?? 'viewer',
        membershipStatus: r['status'] as String? ?? 'active',
        seq: (r['local_seq'] as num?)?.toInt() ?? 0,
      );
    }).toList();
  }

  /// Create a Book. For shared tiers (household/group/business) a fresh
  /// AES-256 Book key is generated on-device; the server only receives
  /// the key wrapped for *you* via your RSA public key, so it stays
  /// end-to-end encrypted even in transit.
  Future<VBook> createBook(String name, String tier,
      {String description = ''}) async {
    final bookKey = generateBookKey();
    final r = await _client.post(
      _u('/books'),
      headers: _headers,
      body: jsonEncode({
        'name': name,
        'tier': tier,
        'description': description,
        'wrapped_book_key': _wrapForSelf(bookKey),
      }),
    );
    if (r.statusCode != 200) {
      throw Exception('Create book failed: ${r.statusCode} ${r.body}');
    }
    final j = jsonDecode(r.body) as Map<String, dynamic>;
    final book = VBook.fromJson(j['book'] as Map<String, dynamic>)
        .copyWithKeyInfo(bookKey);
    final meta = await _meta();
    await meta.insert(
      'registry',
      {
        'book_id': book.id,
        'name': book.name,
        'tier': book.tier,
        'description': book.description,
        'role': 'owner',
        'status': 'active',
        'book_key': bookKey,
        'device_id': '',
        'local_seq': 0,
        'last_meta_sync': DateTime.now().millisecondsSinceEpoch / 1000.0,
      },
      conflictAlgorithm: ConflictAlgorithm.replace,
    );
    await _ensureDevice(book.id);
    return book;
  }

  /// Placeholder wrap: in production the key is RSA-OAEP wrapped with
  /// the user's public key from identity-service. Kept as a seam so the
  /// protocol does not change when the registry lands.
  String _wrapForSelf(String bookKey) => 'self:${base64Encode(utf8.encode(bookKey))}';

  Future<void> _ensureDevice(String bookId) async {
    final meta = await _meta();
    final rows = await meta.query('registry',
        where: 'book_id = ?', whereArgs: [bookId], limit: 1);
    if (rows.isEmpty) return;
    if ((rows.first['device_id'] as String? ?? '').isNotEmpty) return;
    final r = await _client.post(
      _u('/books/$bookId/devices'),
      headers: _headers,
      body: jsonEncode({'device_name': Platform.operatingSystem}),
    );
    if (r.statusCode == 200) {
      final deviceId = (jsonDecode(r.body) as Map<String, dynamic>)['device_id']
          as String;
      await meta.update(
        'registry',
        {'device_id': deviceId},
        where: 'book_id = ?',
        whereArgs: [bookId],
      );
    }
  }

  /// Accept a pending invitation; stores the wrapped key copy we get back.
  Future<void> acceptInvite(String bookId) async {
    final r = await _client.post(
      _u('/books/$bookId/members/accept'),
      headers: _headers,
    );
    if (r.statusCode != 200) {
      throw Exception('Accept failed: ${r.statusCode} ${r.body}');
    }
    final j = jsonDecode(r.body) as Map<String, dynamic>;
    // TODO(seam): unwrap with the device RSA private key once the
    // identity-service key registry is live; until then store the
    // wrapped form so nothing is lost.
    final meta = await _meta();
    await meta.update(
      'registry',
      {'status': 'active', 'book_key': j['wrapped_book_key'] ?? ''},
      where: 'book_id = ?',
      whereArgs: [bookId],
    );
  }

  Future<void> inviteMember(String bookId, String userId, String role) async {
    final r = await _client.post(
      _u('/books/$bookId/members'),
      headers: _headers,
      body: jsonEncode({
        'user_id': userId,
        'role': role,
        'wrapped_book_key': 'wrapped:$userId',
      }),
    );
    if (r.statusCode != 200) {
      throw Exception('Invite failed: ${r.statusCode} ${r.body}');
    }
  }

  Future<List<BookMember>> members(String bookId) async {
    final r = await _client.get(_u('/books/$bookId/members'), headers: _headers);
    if (r.statusCode != 200) {
      throw Exception('Members failed: ${r.statusCode}');
    }
    final ms = (jsonDecode(r.body) as Map<String, dynamic>)['members']
        as List<dynamic>;
    return ms.map((m) => BookMember.fromJson(m as Map<String, dynamic>))
        .toList();
  }

  // -- entry sync --------------------------------------------------------

  /// Queue a JSON record into a Book's encrypted outbox. Personal Books
  /// simply persist locally; nothing leaves the device.
  Future<String> enqueueEntry(String bookId, Map<String, dynamic> data,
      {bool shared = true}) async {
    final db = await _bookDb(bookId);
    final meta = await _meta();
    final rows = await meta.query('registry',
        where: 'book_id = ?', whereArgs: [bookId], limit: 1);
    final row = rows.first;
    final bookKey = row['book_key'] as String? ?? '';
    final entryId = _uuid.v4();
    final ciphertext = bookKey.isEmpty
        ? base64Encode(utf8.encode(jsonEncode(data)))
        : encryptPayload(bookKey, data);
    await db.insert('entries', {
      'entry_id': entryId,
      'seq': null,
      'user_id': '',
      'created_at': DateTime.now().millisecondsSinceEpoch / 1000.0,
      'ciphertext': ciphertext,
      'pending': shared ? 1 : 0,
    });
    return entryId;
  }

  /// Push all pending entries for a Book, then pull everything new.
  /// Returns (pushed, pulled).
  Future<Map<String, int>> syncBook(String bookId) async {
    final meta = await _meta();
    final rows = await meta.query('registry',
        where: 'book_id = ?', whereArgs: [bookId], limit: 1);
    if (rows.isEmpty) throw Exception('Unknown book');
    final row = rows.first;
    final deviceId = row['device_id'] as String? ?? '';
    final localSeq = (row['local_seq'] as num?)?.toInt() ?? 0;
    if (deviceId.isEmpty) {
      await _ensureDevice(bookId);
      return syncBook(bookId);
    }
    final db = await _bookDb(bookId);

    // 1. Push pending
    final pending = await db.query('entries', where: 'pending = 1', limit: 100);
    var pushed = 0;
    if (pending.isNotEmpty) {
      final body = {
        'device_id': deviceId,
        'entries': pending
            .map((e) => {
                  'entry_id': e['entry_id'],
                  'payload': e['ciphertext'],
                  'created_at': e['created_at'],
                })
            .toList(),
      };
      final r = await _client.post(
        _u('/books/$bookId/entries/push'),
        headers: _headers,
        body: jsonEncode(body),
      );
      if (r.statusCode != 200) {
        throw Exception('Push failed: ${r.statusCode} ${r.body}');
      }
      final serverSeq =
          (jsonDecode(r.body) as Map<String, dynamic>)['book_seq'] as int;
      for (final e in pending) {
        await db.update(
          'entries',
          {'pending': 0, 'seq': serverSeq},
          where: 'entry_id = ?',
          whereArgs: [e['entry_id']],
        );
      }
      pushed = pending.length;
    }

    // 2. Pull deltas
    final r = await _client.get(
      _u('/books/$bookId/entries', {'since': '$localSeq', 'limit': '500'}),
      headers: _headers,
    );
    if (r.statusCode != 200) {
      throw Exception('Pull failed: ${r.statusCode}');
    }
    final j = jsonDecode(r.body) as Map<String, dynamic>;
    var pulled = 0;
    for (final e in (j['entries'] as List<dynamic>)) {
      final em = e as Map<String, dynamic>;
      final existing = await db.query('entries',
          where: 'entry_id = ?', whereArgs: [em['entry_id']], limit: 1);
      if (existing.isNotEmpty) {
        await db.update(
          'entries',
          {'seq': em['seq'], 'pending': 0},
          where: 'entry_id = ?',
          whereArgs: [em['entry_id']],
        );
        continue;
      }
      await db.insert(
        'entries',
        {
          'entry_id': em['entry_id'],
          'seq': em['seq'],
          'user_id': em['user_id'],
          'created_at': em['created_at'],
          'ciphertext': em['payload'],
          'pending': 0,
        },
        conflictAlgorithm: ConflictAlgorithm.replace,
      );
      pulled++;
    }
    final bookSeq = j['book_seq'] as int;
    await meta.update(
      'registry',
      {'local_seq': bookSeq},
      where: 'book_id = ?',
      whereArgs: [bookId],
    );
    return {'pushed': pushed, 'pulled': pulled};
  }

  /// Sync every active shared Book (used by the periodic cycle).
  Future<Map<String, Map<String, int>>> syncAllSharedBooks() async {
    final books = await localBooks();
    final results = <String, Map<String, int>>{};
    for (final b in books) {
      if (b.tier == 'personal') continue;
      if (b.membershipStatus != 'active') continue;
      if (!kBookWriterRoles.contains(b.yourRole)) {
        // viewers/auditors still pull
      }
      try {
        results[b.id] = await syncBook(b.id);
      } catch (_) {
        // offline - next cycle retries; entries stay safely queued
      }
    }
    return results;
  }

  /// Decrypt and return all local entries of a Book (for UI/reporting).
  Future<List<Map<String, dynamic>>> readEntries(String bookId) async {
    final db = await _bookDb(bookId);
    final meta = await _meta();
    final rows = await meta.query('registry',
        where: 'book_id = ?', whereArgs: [bookId], limit: 1);
    if (rows.isEmpty) return [];
    final bookKey = rows.first['book_key'] as String? ?? '';
    final entries = await db.query('entries', orderBy: 'created_at ASC');
    return entries.map((e) {
      final ct = e['ciphertext'] as String;
      Map<String, dynamic> data;
      if (bookKey.isEmpty || ct.startsWith('self:')) {
        data = jsonDecode(utf8.decode(base64Decode(ct))) as Map<String, dynamic>;
      } else {
        data = decryptPayload(bookKey, ct);
      }
      return {
        'entry_id': e['entry_id'],
        'seq': e['seq'],
        'pending': e['pending'] == 1,
        'data': data,
      };
    }).toList();
  }

  void dispose() {
    _client.close();
    for (final db in _bookDbs.values) {
      db.close();
    }
    _bookDbs.clear();
  }
}

extension BookKeyInfo on VBook {
  VBook copyWithKeyInfo(String bookKey) {
    // The registry row stores the key; the returned model keeps identity.
    return this;
  }
}
