name: finacc_mobile_client
description: FinAcc mobile client for integrated accounting and finance management.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3 # For local storage
  http: ^1.2.1 # For making API calls
  connectivity_plus: ^6.0.3 # To check network status

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
