apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-backup-pvc
  namespace: vimbai
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
