apiVersion: v1
kind: Secret
metadata:
  name: vimbai-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  neo4j-auth: {{ .Values.secrets.neo4jAuth | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
