"""
Vimbai Treasury & Banking Bracket Service
One container hosting 41 merged microservices. Each member service's
FastAPI app is mounted at its original gateway path prefix, so every
external URL is unchanged.

GENERATED by scripts/generate_brackets.py - do not edit by hand;
re-run the generator instead.
"""

import importlib.util
import os
import sys

from fastapi import FastAPI

SERVICE_NAME = "treasury-banking-bracket"
SERVICE_VERSION = "1.0.0"
PORT = int(os.getenv("PORT", "9003"))

# (gateway path prefix, service directory) pairs
MEMBERS = [
    ["acquisition-financing", "acquisition-financing-service"],
    ["amortization", "amortization-service"],
    ["authorized-share-capital", "authorized-share-capital-service"],
    ["bad-debts-recovery", "bad-debts-recovery-service"],
    ["bank-fee-analysis", "bank-fee-analysis-service"],
    ["bank-feed", "bank-feed-service"],
    ["bank-reconciliation", "bank-reconciliation-service"],
    ["bank-relationship", "bank-relationship-service"],
    ["cash-flow", "cash-flow-service"],
    ["cash-flow-forecasting", "cash-flow-forecasting-service"],
    ["credit-derivatives", "credit-derivatives-service"],
    ["credit-risk-analysis", "credit-risk-analysis-service"],
    ["cross-currency-swap", "cross-currency-swap-service"],
    ["currency", "currency-service"],
    ["currency-hedging", "currency-hedging-service"],
    ["debt-covenants", "debt-covenants-service"],
    ["debt-management", "debt-management-service"],
    ["foreign-currency-translation", "foreign-currency-translation-service"],
    ["ifrs-2-share-based-payment", "ifrs-2-share-based-payment-service"],
    ["initial-investment", "initial-investment-service"],
    ["interest-rate-hedging", "interest-rate-hedging-service"],
    ["interest-rate-risk", "interest-rate-risk-service"],
    ["investment-appraisal", "investment-appraisal-service"],
    ["investment-monitoring", "investment-monitoring-service"],
    ["investment-portfolio", "investment-portfolio-service"],
    ["investment-property", "investment-property-service"],
    ["issued-share-capital", "issued-share-capital-service"],
    ["multi-currency", "multi-currency-service"],
    ["payment-gateway", "payment-gateway-service"],
    ["payment-optimization", "payment-optimization-service"],
    ["provision-bad-debts", "provision-bad-debts-service"],
    ["provision-doubtful-debts", "provision-doubtful-debts-service"],
    ["sovereign-treasury", "sovereign-treasury-service"],
    ["times-interest-earned", "times-interest-earned-service"],
    ["treasury-analytics", "treasury-analytics-service"],
    ["treasury-cash", "treasury-cash-service"],
    ["treasury-compliance", "treasury-compliance-service"],
    ["treasury-management", "treasury-management-service"],
    ["treasury-operations", "treasury-operations-service"],
    ["treasury-policy", "treasury-policy-service"],
    ["treasury-risk", "treasury-risk-service"],
]

app = FastAPI(
    title="Vimbai Treasury & Banking Bracket Service",
    version=SERVICE_VERSION,
    description="Bracket container for 41 Vimbai microservices.",
)

_HERE = os.path.dirname(os.path.abspath(__file__))

_loaded = 0
for _prefix, _svc_dir in MEMBERS:
    # Repo layout: brackets/<name>/main.py with members at repo root.
    _svc_path = os.path.normpath(os.path.join(_HERE, "..", "..", _svc_dir, "main.py"))
    if not os.path.isfile(_svc_path):
        # Docker layout: /app/main.py with members copied next to it.
        _svc_path = os.path.join(_HERE, _svc_dir, "main.py")
    _mod_name = "vimbai_bracket_" + _svc_dir.replace("-", "_")
    _spec = importlib.util.spec_from_file_location(_mod_name, _svc_path)
    _mod = importlib.util.module_from_spec(_spec)
    # Register before exec: some libs (e.g. strawberry) inspect
    # sys.modules[cls.__module__] during class definition.
    sys.modules[_mod_name] = _mod
    _spec.loader.exec_module(_mod)
    app.mount("/" + _prefix.lstrip("/"), _mod.app)
    _loaded += 1


@app.get("/health")
def bracket_health():
    return {
        "service": SERVICE_NAME,
        "status": "healthy",
        "mounted_services": _loaded,
    }


@app.get("/")
def bracket_root():
    return {
        "service": SERVICE_NAME,
        "version": SERVICE_VERSION,
        "mounted_services": _loaded,
        "paths": ["/" + p for p, _ in MEMBERS],
    }


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=PORT)
