apiVersion: v1
kind: Secret
metadata:
  name: vimbai-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  NEO4J_PASSWORD: {{ .Values.neo4j.auth.password | quote }}
  JWT_SECRET: {{ .Values.jwtSecret | default "CHANGE_ME" | quote }}
  RABBITMQ_USER: {{ .Values.rabbitmq.auth.user | quote }}
  RABBITMQ_PASS: {{ .Values.rabbitmq.auth.password | quote }}
