"""
Vimbai Operations & Inventory Bracket Service
One container hosting 9 merged microservices. Each member service's
FastAPI app is mounted at its original gateway path prefix, so every
external URL is unchanged.

GENERATED by scripts/generate_brackets.py - do not edit by hand;
re-run the generator instead.
"""

import importlib.util
import os
import sys

from fastapi import FastAPI

SERVICE_NAME = "operations-inventory-bracket"
SERVICE_VERSION = "1.0.0"
PORT = int(os.getenv("PORT", "9009"))

# (gateway path prefix, service directory) pairs
MEMBERS = [
    ["biological-assets", "biological-assets-service"],
    ["data-warehouse", "data-warehouse-service"],
    ["fixed-assets", "fixed-assets-service"],
    ["fixed-assets-register", "fixed-assets-register-service"],
    ["inventory-valuation", "inventory-valuation-service"],
    ["order-acceptance", "order-acceptance-service"],
    ["project-accounting", "project-accounting-service"],
    ["project-appraisal", "project-appraisal-service"],
    ["subscription-plans", "subscription-plans-service"],
]

app = FastAPI(
    title="Vimbai Operations & Inventory Bracket Service",
    version=SERVICE_VERSION,
    description="Bracket container for 9 Vimbai microservices.",
)

_HERE = os.path.dirname(os.path.abspath(__file__))

_loaded = 0
for _prefix, _svc_dir in MEMBERS:
    # Repo layout: brackets/<name>/main.py with members at repo root.
    _svc_path = os.path.normpath(os.path.join(_HERE, "..", "..", _svc_dir, "main.py"))
    if not os.path.isfile(_svc_path):
        # Docker layout: /app/main.py with members copied next to it.
        _svc_path = os.path.join(_HERE, _svc_dir, "main.py")
    _mod_name = "vimbai_bracket_" + _svc_dir.replace("-", "_")
    _spec = importlib.util.spec_from_file_location(_mod_name, _svc_path)
    _mod = importlib.util.module_from_spec(_spec)
    # Register before exec: some libs (e.g. strawberry) inspect
    # sys.modules[cls.__module__] during class definition.
    sys.modules[_mod_name] = _mod
    _spec.loader.exec_module(_mod)
    app.mount("/" + _prefix.lstrip("/"), _mod.app)
    _loaded += 1


@app.get("/health")
def bracket_health():
    return {
        "service": SERVICE_NAME,
        "status": "healthy",
        "mounted_services": _loaded,
    }


@app.get("/")
def bracket_root():
    return {
        "service": SERVICE_NAME,
        "version": SERVICE_VERSION,
        "mounted_services": _loaded,
        "paths": ["/" + p for p, _ in MEMBERS],
    }


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=PORT)
